"""AutoRefine CLI — manage prompts, view analytics, launch the dashboard.

Usage::

    autorefine init                       # interactive setup
    autorefine dashboard                  # launch web UI
    autorefine prompts list               # list prompt keys
    autorefine prompts show <key>         # print active prompt
    autorefine prompts diff <key> <v1> <v2>
    autorefine prompts rollback <key> <v> # rollback with confirmation
    autorefine stats                      # feedback/cost summary
    autorefine export <key> --format json # export history
    autorefine reset <key> --confirm      # wipe data
"""

from __future__ import annotations

import difflib
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

try:
    import click
except ImportError:
    print("The click package is required for the CLI: pip install click", file=sys.stderr)
    sys.exit(1)

# ── Optional rich formatting ─────────────────────────────────────────
try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.syntax import Syntax
    from rich.table import Table
    _console = Console()
    _HAS_RICH = True
except ImportError:
    _HAS_RICH = False
    _console = None  # type: ignore[assignment]


def _print(text: str = "", **kw: Any) -> None:
    if _HAS_RICH:
        _console.print(text, **kw)
    else:
        click.echo(text)


def _get_store():
    """Load the store from env/config."""
    from autorefine.config import AutoRefineSettings
    from autorefine.storage import get_store
    cfg = AutoRefineSettings()
    return get_store(config=cfg), cfg


# ═══════════════════════════════════════════════════════════════════════
# Root group
# ═══════════════════════════════════════════════════════════════════════

_BANNER = r"""
    _         _        ____       __ _
   / \  _   _| |_ ___ |  _ \ ___ / _(_)_ __   ___
  / _ \| | | | __/ _ \| |_) / _ \ |_| | '_ \ / _ \
 / ___ \ |_| | || (_) |  _ <  __/  _| | | | |  __/
/_/   \_\__,_|\__\___/|_| \_\___|_| |_|_| |_|\___|

  by  U P W E L L  D I G I T A L  S O L U T I O N S
"""


@click.group()
@click.version_option(package_name="autorefine")
def main():
    """AutoRefine -- make any AI app progressively smarter.

    Built by Upwell Digital Solutions -- upwelldigitalsolutions.com
    """
    pass


# ═══════════════════════════════════════════════════════════════════════
# autorefine init
# ═══════════════════════════════════════════════════════════════════════

@main.command()
def init():
    """Interactive setup -- creates .env and a starter script."""
    if _HAS_RICH:
        _console.print(f"[bold blue]{_BANNER}[/bold blue]")
    else:
        click.echo(_BANNER)

    mode = click.prompt(
        "How do you want to run AutoRefine?\n"
        "  1. Self-hosted (provide your own LLM API keys)\n"
        "  2. AutoRefine Cloud (get an API key from autorefine.dev)\n"
        "Choose",
        type=click.Choice(["1", "2"]), default="1",
    )

    if mode == "2":
        _print("\nVisit https://autorefine.dev/signup to get your API key.")
        api_key = click.prompt("Paste your AutoRefine API key (ar_live_...)", default="", show_default=False)
        model = click.prompt("Model", default="gpt-4o")
        env_path = Path(".env")
        lines = [
            f"AUTOREFINE_API_KEY={api_key}",
            f"AUTOREFINE_MODEL={model}",
            "AUTOREFINE_AUTO_LEARN=true",
        ]
        env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        _print(f"\n  Wrote {env_path.resolve()}")
        _print("  No refiner key needed -- AutoRefine Cloud handles refinement.")

        starter = Path("quickstart.py")
        if not starter.exists():
            starter.write_text(
                '"""AutoRefine Cloud quickstart -- generated by `autorefine init`."""\n\n'
                'from autorefine import AutoRefine\n\n'
                'client = AutoRefine()  # reads .env automatically -- routes through cloud\n'
                'client.set_system_prompt("You are a helpful assistant.")\n\n'
                'resp = client.complete("You are a helpful assistant.", "Hello!")\n'
                'print(resp.text)\n\n'
                '# client.feedback(resp.id, "thumbs_up")\n',
                encoding="utf-8",
            )
            _print(f"  Wrote {starter.resolve()}")
        _print("\n  Run `python quickstart.py` to get started!")
        return

    api_key = click.prompt("Primary LLM API key (e.g. sk-...)", default="", show_default=False)
    model = click.prompt("Model", default="gpt-4o")
    refiner_key = click.prompt("Refiner API key (Anthropic, for auto-refinement)", default="", show_default=False)
    storage = click.prompt("Storage backend", type=click.Choice(["json", "sqlite", "postgres"]), default="json")

    db_url = ""
    if storage == "postgres":
        db_url = click.prompt("PostgreSQL connection URL")

    # Write .env
    env_path = Path(".env")
    lines = [
        f"AUTOREFINE_API_KEY={api_key}",
        f"AUTOREFINE_MODEL={model}",
        f"AUTOREFINE_STORAGE_BACKEND={storage}",
    ]
    if refiner_key:
        lines.append(f"AUTOREFINE_REFINER_KEY={refiner_key}")
        lines.append("AUTOREFINE_AUTO_LEARN=true")
    if db_url:
        lines.append(f"AUTOREFINE_DATABASE_URL={db_url}")

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _print(f"\n  Wrote {env_path.resolve()}")

    # Write starter script
    starter = Path("quickstart.py")
    if not starter.exists():
        starter.write_text(
            '"""AutoRefine quickstart — generated by `autorefine init`."""\n\n'
            'from autorefine import AutoRefine\n\n'
            'client = AutoRefine()  # reads .env automatically\n'
            'client.set_system_prompt("You are a helpful assistant.")\n\n'
            'resp = client.complete("You are a helpful assistant.", "Hello!")\n'
            'print(resp.text)\n\n'
            '# client.feedback(resp.id, "thumbs_up")\n',
            encoding="utf-8",
        )
        _print(f"  Wrote {starter.resolve()}")

    _print("\n  Run [bold]python quickstart.py[/bold] to get started!" if _HAS_RICH
           else "\n  Run `python quickstart.py` to get started!")


# ═══════════════════════════════════════════════════════════════════════
# autorefine dashboard
# ═══════════════════════════════════════════════════════════════════════

@main.command()
@click.option("--port", default=8787, help="Port for the dashboard server.")
@click.option("--password", default="", help="Basic auth password.")
def dashboard(port: int, password: str):
    """Launch the web dashboard."""
    from autorefine.dashboard.server import run_dashboard
    store, cfg = _get_store()
    pw = password or cfg.dashboard_password
    _print(f"Starting dashboard on http://localhost:{port}")
    run_dashboard(store, port=port, password=pw)


# ═══════════════════════════════════════════════════════════════════════
# autorefine prompts *
# ═══════════════════════════════════════════════════════════════════════

@main.group("prompts")
def prompts_group():
    """Manage prompt versions."""
    pass


@prompts_group.command("list")
def prompts_list():
    """List all prompt keys and their active versions."""
    store, _ = _get_store()

    # Discover prompt keys by scanning all versions
    store.get_prompt_history("default")
    keys = {"default"}
    # Try common keys — the store doesn't have a "list all keys" method
    for k in ("default", "support-billing", "support-technical", "content-writer"):
        h = store.get_prompt_history(k)
        if h:
            keys.add(k)

    if _HAS_RICH:
        table = Table(title="Prompt Keys")
        table.add_column("Key", style="cyan")
        table.add_column("Active Version", style="green")
        table.add_column("Total Versions", style="yellow")
        for k in sorted(keys):
            active = store.get_active_prompt(k)
            history = store.get_prompt_history(k)
            if history:
                table.add_row(k, f"v{active.version}" if active else "-", str(len(history)))
        _console.print(table)
    else:
        for k in sorted(keys):
            active = store.get_active_prompt(k)
            history = store.get_prompt_history(k)
            if history:
                v = f"v{active.version}" if active else "-"
                click.echo(f"  {k:30s}  active={v}  versions={len(history)}")


@prompts_group.command("show")
@click.argument("key", default="default")
def prompts_show(key: str):
    """Print the current active prompt text."""
    store, _ = _get_store()
    active = store.get_active_prompt(key)
    if active is None:
        _print(f"No active prompt for key '{key}'")
        return

    if _HAS_RICH:
        _console.print(Panel(
            active.system_prompt,
            title=f"[cyan]{key}[/cyan] v{active.version}",
            subtitle=active.changelog or "",
            border_style="green",
        ))
    else:
        click.echo(f"--- {key} v{active.version} ---")
        click.echo(active.system_prompt)
        if active.changelog:
            click.echo(f"\nChangelog: {active.changelog}")


@prompts_group.command("diff")
@click.argument("key", default="default")
@click.argument("v1", type=int)
@click.argument("v2", type=int)
def prompts_diff(key: str, v1: int, v2: int):
    """Show a colored diff between two prompt versions."""
    store, _ = _get_store()
    pv1 = store.get_prompt_version(key, v1)
    pv2 = store.get_prompt_version(key, v2)
    if pv1 is None:
        _print(f"Version {v1} not found for key '{key}'")
        return
    if pv2 is None:
        _print(f"Version {v2} not found for key '{key}'")
        return

    diff_lines = list(difflib.unified_diff(
        pv1.system_prompt.splitlines(keepends=True),
        pv2.system_prompt.splitlines(keepends=True),
        fromfile=f"v{v1}", tofile=f"v{v2}",
    ))

    if not diff_lines:
        _print("No differences.")
        return

    if _HAS_RICH:
        _console.print(Syntax("".join(diff_lines), "diff", theme="monokai"))
    else:
        for line in diff_lines:
            if line.startswith("+"):
                click.secho(line, fg="green", nl=False)
            elif line.startswith("-"):
                click.secho(line, fg="red", nl=False)
            elif line.startswith("@@"):
                click.secho(line, fg="cyan", nl=False)
            else:
                click.echo(line, nl=False)


@prompts_group.command("rollback")
@click.argument("key", default="default")
@click.argument("version", type=int)
def prompts_rollback(key: str, version: int):
    """Roll back to a specific prompt version."""
    store, _ = _get_store()
    pv = store.get_prompt_version(key, version)
    if pv is None:
        _print(f"Version {version} not found for key '{key}'")
        return

    _print(f"Rolling back '{key}' to v{version}:")
    _print(f"  {pv.system_prompt[:120]}{'...' if len(pv.system_prompt) > 120 else ''}")

    if not click.confirm("Proceed?"):
        _print("Cancelled.")
        return

    store.set_active_version(key, version)
    _print(f"Rolled back to v{version}")


# ═══════════════════════════════════════════════════════════════════════
# autorefine stats
# ═══════════════════════════════════════════════════════════════════════

@main.command()
def stats():
    """Print a summary table of feedback, scores, and costs."""
    store, _ = _get_store()

    keys = set()
    for k in ("default", "support-billing", "support-technical", "content-writer"):
        if store.get_prompt_history(k):
            keys.add(k)
    if not keys:
        keys.add("default")

    if _HAS_RICH:
        table = Table(title="AutoRefine Stats (last 30 days)")
        table.add_column("Prompt Key", style="cyan")
        table.add_column("Interactions", justify="right")
        table.add_column("Feedback", justify="right")
        table.add_column("Avg Score", justify="right")
        table.add_column("Versions", justify="right")
        table.add_column("Active", style="green", justify="right")
        for k in sorted(keys):
            a = store.get_analytics(k, days=30)
            table.add_row(
                k,
                str(a["total_interactions"]),
                str(a["total_feedback"]),
                f"{a['average_score']:+.2f}",
                str(a["total_versions"]),
                f"v{a['active_version']}",
            )
        _console.print(table)
        cost = store.get_monthly_refiner_cost()
        _console.print(f"\n  Monthly refiner cost: [bold]${cost:.4f}[/bold]")
    else:
        click.echo(f"{'Key':30s} {'Ix':>6s} {'FB':>6s} {'Score':>7s} {'Ver':>4s} {'Active':>7s}")
        click.echo("-" * 70)
        for k in sorted(keys):
            a = store.get_analytics(k, days=30)
            click.echo(
                f"{k:30s} {a['total_interactions']:6d} {a['total_feedback']:6d} "
                f"{a['average_score']:+7.2f} {a['total_versions']:4d} v{a['active_version']:>5d}"
            )
        click.echo(f"\nMonthly refiner cost: ${store.get_monthly_refiner_cost():.4f}")


# ═══════════════════════════════════════════════════════════════════════
# autorefine export
# ═══════════════════════════════════════════════════════════════════════

@main.command()
@click.argument("key", default="default")
@click.option("--format", "fmt", type=click.Choice(["json", "md"]), default="json", help="Output format.")
def export(key: str, fmt: str):
    """Export the full prompt evolution history."""
    store, _ = _get_store()
    history = store.get_prompt_history(key)
    if not history:
        _print(f"No history for key '{key}'")
        return

    if fmt == "json":
        data = [
            {
                "version": pv.version,
                "system_prompt": pv.system_prompt,
                "parent_version": pv.parent_version,
                "changelog": pv.changelog,
                "is_active": pv.is_active,
                "created_at": pv.created_at.isoformat(),
                "performance_score": pv.performance_score,
            }
            for pv in history
        ]
        click.echo(json.dumps({"prompt_key": key, "versions": data}, indent=2))

    elif fmt == "md":
        click.echo(f"# Prompt History: `{key}`\n")
        for pv in history:
            active = " **(active)**" if pv.is_active else ""
            click.echo(f"## Version {pv.version}{active}\n")
            click.echo(f"- Created: {pv.created_at.isoformat()}")
            if pv.changelog:
                click.echo(f"- Changelog: {pv.changelog}")
            if pv.parent_version is not None:
                click.echo(f"- Parent: v{pv.parent_version}")
            click.echo(f"\n```\n{pv.system_prompt}\n```\n")


# ═══════════════════════════════════════════════════════════════════════
# autorefine reset
# ═══════════════════════════════════════════════════════════════════════

@main.command()
@click.argument("key", default="default")
@click.option("--confirm", is_flag=True, help="Skip confirmation prompt.")
def reset(key: str, confirm: bool):
    """Wipe all data for a prompt key."""
    store, _ = _get_store()

    history = store.get_prompt_history(key)
    feedback = store.get_feedback(prompt_key=key, limit=100_000)
    interactions = store.get_interactions(prompt_key=key, limit=100_000)

    _print(f"This will delete for key '{key}':")
    _print(f"  {len(history)} prompt versions")
    _print(f"  {len(interactions)} interactions")
    _print(f"  {len(feedback)} feedback signals")

    if not confirm and not click.confirm("Are you sure? This cannot be undone"):
        _print("Cancelled.")
        return

    # Purge by setting a far-future cutoff (purges everything)
    # Then deactivate all versions
    count = store.purge_old_data(datetime.now(timezone.utc) + timedelta(days=1))
    store.set_active_version(key, -1)
    _print(f"Deleted {count} records.")


# ═══════════════════════════════════════════════════════════════════════
# autorefine cloud *
# ═══════════════════════════════════════════════════════════════════════

@main.group("cloud")
def cloud_group():
    """AutoRefine Cloud key management and usage."""
    pass


@cloud_group.command("login")
def cloud_login():
    """Authenticate with AutoRefine Cloud."""
    import webbrowser
    _print("Opening autorefine.dev/signup in your browser...")
    try:
        webbrowser.open("https://autorefine.dev/signup")
    except Exception:
        _print("Could not open browser. Visit https://autorefine.dev/signup manually.")
    key = click.prompt("Paste your API key (ar_live_...)", default="", show_default=False)
    if key:
        env_path = Path(".env")
        existing = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
        # Replace or append
        lines = [l for l in existing.splitlines() if not l.startswith("AUTOREFINE_API_KEY=")]
        lines.append(f"AUTOREFINE_API_KEY={key}")
        env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        _print(f"Saved to {env_path.resolve()}")


@cloud_group.group("keys")
def cloud_keys_group():
    """Manage API keys."""
    pass


@cloud_keys_group.command("list")
def cloud_keys_list():
    """List API keys for your organization."""
    import httpx
    _, cfg = _get_store()
    if not cfg.detect_cloud_mode():
        _print("Not in cloud mode. Set AUTOREFINE_API_KEY=ar_live_...")
        return
    try:
        resp = httpx.get(
            f"{cfg.cloud_base_url}/api/keys",
            headers={"Authorization": f"Bearer {cfg.api_key}"},
            timeout=10,
        )
        data = resp.json()
        if _HAS_RICH:
            table = Table(title="API Keys")
            table.add_column("Prefix", style="cyan")
            table.add_column("Name")
            table.add_column("Active", style="green")
            table.add_column("Created")
            for k in data.get("keys", []):
                table.add_row(k["key_prefix"], k.get("name", ""), str(k["is_active"]), k.get("created_at", "")[:10])
            _console.print(table)
        else:
            for k in data.get("keys", []):
                click.echo(f"  {k['key_prefix']}  name={k.get('name', '')}  active={k['is_active']}")
    except Exception as exc:
        _print(f"Error: {exc}")


@cloud_keys_group.command("create")
@click.option("--name", default="", help="Human label for the key.")
@click.option("--type", "key_type", type=click.Choice(["live", "test"]), default="live")
def cloud_keys_create(name: str, key_type: str):
    """Generate a new API key."""
    import httpx
    _, cfg = _get_store()
    if not cfg.detect_cloud_mode():
        _print("Not in cloud mode. Set AUTOREFINE_API_KEY=ar_live_...")
        return
    try:
        resp = httpx.post(
            f"{cfg.cloud_base_url}/api/keys",
            headers={"Authorization": f"Bearer {cfg.api_key}"},
            json={"name": name, "key_type": key_type},
            timeout=10,
        )
        data = resp.json()
        plaintext = data.get("key", "")
        _print(f"\nNew API key (shown once):\n")
        _print(f"  {plaintext}")
        _print(f"\nSave this key securely -- it cannot be retrieved again.")
    except Exception as exc:
        _print(f"Error: {exc}")


@cloud_keys_group.command("revoke")
@click.argument("key_id")
def cloud_keys_revoke(key_id: str):
    """Revoke an API key."""
    import httpx
    _, cfg = _get_store()
    if not cfg.detect_cloud_mode():
        _print("Not in cloud mode.")
        return
    if not click.confirm(f"Revoke key {key_id}?"):
        return
    try:
        resp = httpx.post(
            f"{cfg.cloud_base_url}/api/keys/{key_id}/revoke",
            headers={"Authorization": f"Bearer {cfg.api_key}"},
            timeout=10,
        )
        _print(f"Result: {resp.json().get('status', 'unknown')}")
    except Exception as exc:
        _print(f"Error: {exc}")


@cloud_group.command("usage")
@click.option("--daily", is_flag=True, help="Show daily breakdown.")
def cloud_usage(daily: bool):
    """Show current month's usage summary."""
    import httpx
    _, cfg = _get_store()
    if not cfg.detect_cloud_mode():
        _print("Not in cloud mode. Set AUTOREFINE_API_KEY=ar_live_...")
        return
    try:
        if daily:
            resp = httpx.get(
                f"{cfg.cloud_base_url}/api/usage/daily?days=30",
                headers={"Authorization": f"Bearer {cfg.api_key}"},
                timeout=10,
            )
            data = resp.json()
            if _HAS_RICH:
                table = Table(title="Daily Usage (last 30 days)")
                table.add_column("Date")
                table.add_column("Calls", justify="right")
                table.add_column("Tokens", justify="right")
                table.add_column("Cost", justify="right", style="yellow")
                for d in data.get("daily", []):
                    tokens = d["total_input_tokens"] + d["total_output_tokens"]
                    table.add_row(
                        d["date"], str(d["total_calls"]),
                        f"{tokens:,}", f"${d['total_customer_cost']:.4f}",
                    )
                _console.print(table)
            else:
                for d in data.get("daily", []):
                    tokens = d["total_input_tokens"] + d["total_output_tokens"]
                    click.echo(f"  {d['date']}  calls={d['total_calls']}  tokens={tokens:,}  cost=${d['total_customer_cost']:.4f}")
        else:
            resp = httpx.get(
                f"{cfg.cloud_base_url}/api/usage",
                headers={"Authorization": f"Bearer {cfg.api_key}"},
                timeout=10,
            )
            data = resp.json()
            _print(f"Monthly spend:   ${data.get('monthly_spend', 0):.4f}")
            _print(f"Monthly cap:     ${data.get('monthly_cap', 0):.2f}")
            _print(f"Utilization:     {data.get('utilization_pct', 0):.1f}%")
    except Exception as exc:
        _print(f"Error: {exc}")


if __name__ == "__main__":
    main()
