"""Pydantic data models for AutoRefine.

Every model is fully JSON-serialisable via ``model.model_dump(mode="json")``.
Fields use strict validation where it matters (scores clamped, tokens
non-negative, etc.) and ship sensible defaults so callers only need to supply
the fields they actually have.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utc_now() -> datetime:
    """Return the current time in UTC."""
    return datetime.now(timezone.utc)


def _new_id() -> str:
    """Generate a short unique identifier (16 hex chars)."""
    return uuid.uuid4().hex[:16]


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class FeedbackType(str, Enum):
    """Categorises the kind of feedback a user gave."""

    POSITIVE = "positive"
    """The user explicitly approved the response."""

    NEGATIVE = "negative"
    """The user explicitly disapproved of the response."""

    CORRECTION = "correction"
    """The user supplied a corrected / preferred response."""

    IMPLICIT_REASK = "implicit_reask"
    """The user immediately re-asked the same question — implies dissatisfaction."""

    IMPLICIT_ABANDON = "implicit_abandon"
    """The user abandoned the conversation shortly after — weak negative signal."""


class MessageRole(str, Enum):
    """Standard chat-message roles."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


# ---------------------------------------------------------------------------
# Chat messages
# ---------------------------------------------------------------------------

class Message(BaseModel):
    """A single chat message with a role and text content."""

    role: MessageRole = Field(
        description="Who produced this message (system, user, or assistant).",
    )
    content: str = Field(
        description="The text body of the message.",
    )


# ---------------------------------------------------------------------------
# Interaction — a full request / response pair
# ---------------------------------------------------------------------------

class Interaction(BaseModel):
    """A complete LLM request/response round-trip.

    Captures everything needed to replay or analyse the call: the messages
    sent, the system prompt in effect, the raw response, token counts, cost,
    and timing.
    """

    id: str = Field(
        default_factory=_new_id,
        description="Unique interaction identifier (auto-generated 16-char hex).",
    )
    prompt_key: str = Field(
        default="default",
        description="Logical prompt namespace this interaction belongs to.",
    )
    prompt_version: int = Field(
        default=0,
        ge=0,
        description="Version of the system prompt that was active for this call.",
    )
    system_prompt: str = Field(
        default="",
        description="The full system prompt that was injected into this call.",
    )
    messages: list[Message] = Field(
        default_factory=list,
        description="The conversation messages sent to the model.",
    )
    response_text: str = Field(
        default="",
        description="The model's raw text response.",
    )
    input_tokens: int = Field(
        default=0,
        ge=0,
        description="Number of input tokens consumed by this call.",
    )
    output_tokens: int = Field(
        default=0,
        ge=0,
        description="Number of output tokens generated by this call.",
    )
    model: str = Field(
        default="",
        description="Model identifier used for this call (e.g. 'gpt-4o').",
    )
    provider: str = Field(
        default="",
        description="Provider that served the request (e.g. 'openai', 'anthropic').",
    )
    cost_usd: float = Field(
        default=0.0,
        ge=0.0,
        description="Estimated cost of this call in US dollars.",
    )
    created_at: datetime = Field(
        default_factory=_utc_now,
        description="UTC timestamp when the interaction was recorded.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary key-value pairs for caller-specific context.",
    )


# ---------------------------------------------------------------------------
# Feedback signal
# ---------------------------------------------------------------------------

class FeedbackSignal(BaseModel):
    """A single piece of user feedback tied to an interaction.

    Feedback can be explicit (thumbs up/down, written correction) or implicit
    (re-asking the same question, abandoning the conversation).  Each signal
    carries a normalised score and a confidence weight so the refiner can
    weigh them appropriately.
    """

    id: str = Field(
        default_factory=_new_id,
        description="Unique feedback identifier.",
    )
    interaction_id: str = Field(
        description="ID of the interaction this feedback refers to.",
    )
    feedback_type: FeedbackType = Field(
        description="Category of the feedback signal.",
    )
    score: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Normalised sentiment score from -1.0 (worst) to 1.0 (best).",
    )
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="How reliable this signal is (1.0 = explicit, <0.5 = implicit).",
    )
    comment: str = Field(
        default="",
        description="Optional free-text comment from the user.",
    )
    correction: str = Field(
        default="",
        description="If feedback_type is CORRECTION, the user's preferred response.",
    )
    user_id: str = Field(
        default="",
        description="Optional identifier for the end-user who gave feedback.",
    )
    created_at: datetime = Field(
        default_factory=_utc_now,
        description="UTC timestamp when the feedback was submitted.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary key-value pairs for caller-specific context.",
    )

    @field_validator("score")
    @classmethod
    def _clamp_score(cls, v: float) -> float:
        """Ensure score stays within [-1, 1] even if a raw value slips through."""
        return max(-1.0, min(1.0, v))

    @field_validator("confidence")
    @classmethod
    def _clamp_confidence(cls, v: float) -> float:
        """Ensure confidence stays within [0, 1]."""
        return max(0.0, min(1.0, v))


# ---------------------------------------------------------------------------
# Prompt versioning
# ---------------------------------------------------------------------------

class PromptVersion(BaseModel):
    """An immutable, versioned snapshot of a system prompt.

    Only one version per ``prompt_key`` is active at a time.  Previous
    versions are retained for rollback and analytics.
    """

    version: int = Field(
        ge=1,
        description="Monotonically increasing version number within its prompt_key.",
    )
    prompt_key: str = Field(
        default="default",
        description="Logical namespace that groups related prompt versions.",
    )
    system_prompt: str = Field(
        description="The full text of the system prompt for this version.",
    )
    parent_version: int | None = Field(
        default=None,
        description="Version this was derived from (None for the initial prompt).",
    )
    changelog: str = Field(
        default="",
        description="Human-readable summary of what changed from the parent.",
    )
    performance_score: float = Field(
        default=0.0,
        description="Rolling average feedback score while this version was active.",
    )
    interaction_count: int = Field(
        default=0,
        ge=0,
        description="Total interactions served while this version was active.",
    )
    is_active: bool = Field(
        default=True,
        description="Whether this is the currently active version for its prompt_key.",
    )
    created_at: datetime = Field(
        default_factory=_utc_now,
        description="UTC timestamp when this version was created.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary key-value pairs for caller-specific context.",
    )


class PromptCandidate(BaseModel):
    """A proposed prompt that is pending A/B validation before promotion.

    Created by the refiner, then either sent to an A/B test or promoted
    directly depending on configuration.
    """

    prompt_key: str = Field(
        default="default",
        description="Prompt namespace this candidate targets.",
    )
    system_prompt: str = Field(
        description="The full text of the proposed system prompt.",
    )
    parent_version: int = Field(
        ge=0,
        description="The active version number this candidate was derived from.",
    )
    changelog: str = Field(
        default="",
        description="Summary of what changed and why.",
    )
    reasoning: str = Field(
        default="",
        description="The refiner's analysis of feedback patterns that motivated the change.",
    )
    expected_improvements: list[str] = Field(
        default_factory=list,
        description="Concrete improvements the refiner expects from this candidate.",
    )
    created_at: datetime = Field(
        default_factory=_utc_now,
        description="UTC timestamp when the candidate was generated.",
    )


# ---------------------------------------------------------------------------
# Refinement result from the refiner model
# ---------------------------------------------------------------------------

class RefinementResult(BaseModel):
    """Structured output from the refiner model after analysing feedback.

    Contains the rewritten prompt along with the refiner's full reasoning
    so developers can audit *why* a change was proposed.
    """

    new_prompt: str = Field(
        description="The complete rewritten system prompt.",
    )
    changelog: str = Field(
        default="",
        description="Brief description of what changed and why.",
    )
    reasoning: str = Field(
        default="",
        description="The refiner's analysis of feedback patterns.",
    )
    gaps_identified: list[str] = Field(
        default_factory=list,
        description="Specific gaps in the original prompt that the refiner found.",
    )
    expected_improvements: list[str] = Field(
        default_factory=list,
        description="Concrete improvements expected from the new prompt.",
    )
    feedback_summary: str = Field(
        default="",
        description="Statistical summary of the feedback batch that triggered this refinement.",
    )
    created_at: datetime = Field(
        default_factory=_utc_now,
        description="UTC timestamp when the refinement was produced.",
    )


# ---------------------------------------------------------------------------
# Cost tracking
# ---------------------------------------------------------------------------

class CostEntry(BaseModel):
    """A single cost record for an LLM API call.

    Tracks token usage and dollar cost for both primary (user-facing) calls
    and refiner (prompt-improvement) calls so operators can monitor spend.
    """

    id: str = Field(
        default_factory=_new_id,
        description="Unique cost-entry identifier.",
    )
    interaction_id: str = Field(
        default="",
        description="ID of the interaction this cost is associated with (empty for refiner calls).",
    )
    provider: str = Field(
        default="",
        description="Provider that served the call (e.g. 'openai', 'anthropic').",
    )
    model: str = Field(
        default="",
        description="Model identifier (e.g. 'gpt-4o', 'claude-sonnet-4-20250514').",
    )
    input_tokens: int = Field(
        default=0,
        ge=0,
        description="Number of input tokens consumed.",
    )
    output_tokens: int = Field(
        default=0,
        ge=0,
        description="Number of output tokens generated.",
    )
    cost_usd: float = Field(
        default=0.0,
        ge=0.0,
        description="Cost of this call in US dollars.",
    )
    call_type: Literal["primary", "refiner"] = Field(
        default="primary",
        description="Whether this was a user-facing call ('primary') or a prompt-refinement call ('refiner').",
    )
    created_at: datetime = Field(
        default_factory=_utc_now,
        description="UTC timestamp when this cost was recorded.",
    )

    @property
    def is_refiner_call(self) -> bool:
        """Convenience property for backward-compatible boolean checks."""
        return self.call_type == "refiner"


# ---------------------------------------------------------------------------
# LLM response wrapper
# ---------------------------------------------------------------------------

class CompletionResponse(BaseModel):
    """Wrapper returned to the caller after a chat/complete call.

    Contains the model output alongside billing metadata and the prompt
    version that was active at call time.
    """

    id: str = Field(
        default_factory=_new_id,
        description="The interaction ID (matches the stored Interaction).",
    )
    text: str = Field(
        default="",
        description="The model's text response.",
    )
    messages: list[Message] = Field(
        default_factory=list,
        description="Full message list including the assistant's reply.",
    )
    model: str = Field(
        default="",
        description="Model identifier that produced this response.",
    )
    input_tokens: int = Field(
        default=0,
        ge=0,
        description="Input tokens consumed.",
    )
    output_tokens: int = Field(
        default=0,
        ge=0,
        description="Output tokens generated.",
    )
    cost_usd: float = Field(
        default=0.0,
        ge=0.0,
        description="Estimated cost in US dollars.",
    )
    prompt_version: int = Field(
        default=0,
        ge=0,
        description="Version of the system prompt that was active for this call.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary key-value pairs for caller-specific context.",
    )


# ---------------------------------------------------------------------------
# A/B test state
# ---------------------------------------------------------------------------

class ABTest(BaseModel):
    """Tracks the state of an A/B test between two prompt versions.

    Traffic is split between ``control_version`` (the current active prompt)
    and ``candidate_version`` (the proposed improvement).  Once both variants
    accumulate enough interactions the test auto-resolves.
    """

    id: str = Field(
        default_factory=_new_id,
        description="Unique A/B test identifier.",
    )
    prompt_key: str = Field(
        default="default",
        description="Prompt namespace under test.",
    )
    control_version: int = Field(
        ge=0,
        description="Version number of the current active (control) prompt.",
    )
    candidate_version: int = Field(
        ge=0,
        description="Version number of the candidate prompt being tested.",
    )
    split_ratio: float = Field(
        default=0.2,
        ge=0.0,
        le=1.0,
        description="Fraction of traffic routed to the candidate (0.0–1.0).",
    )
    control_interactions: int = Field(
        default=0,
        ge=0,
        description="Number of interactions served by the control variant.",
    )
    candidate_interactions: int = Field(
        default=0,
        ge=0,
        description="Number of interactions served by the candidate variant.",
    )
    control_score: float = Field(
        default=0.0,
        description="Rolling average feedback score for the control variant.",
    )
    candidate_score: float = Field(
        default=0.0,
        description="Rolling average feedback score for the candidate variant.",
    )
    is_active: bool = Field(
        default=True,
        description="Whether this test is currently running.",
    )
    created_at: datetime = Field(
        default_factory=_utc_now,
        description="UTC timestamp when the test started.",
    )
    completed_at: datetime | None = Field(
        default=None,
        description="UTC timestamp when the test finished (None if still running).",
    )
    result: str = Field(
        default="",
        description="Outcome: 'promoted', 'rejected', 'superseded', or '' (still running).",
    )
